package Eventos;

import Enumeracion.TipoDeporte;
import Principal.Login;
import Principal.MenuEventos;
import Usuarios.Administrador;
import Usuarios.Contenidos;
import Usuarios.ManejoUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public final class CrearDeportivo extends javax.swing.JFrame {

    /**
     * Creates new form CrearDeportivo
     */
    private TipoDeporte seleccionado;
    public CrearDeportivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreEquipo1 = new javax.swing.JTextField();
        codigoEvento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tituloEvento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreEquipo2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionEvento = new javax.swing.JTextArea();
        botonVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tipoDeporte = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        montoEvento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        calendarioEvento = new com.toedter.calendar.JDateChooser();
        crearEvento = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cantidadPersonas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel2.setText("Evento Deportivo");

        jLabel5.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel5.setText("Monto del Evento:");

        jLabel3.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        nombreEquipo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        codigoEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de deporte:");

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel4.setText("Título:");

        tituloEvento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tituloEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloEventoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel6.setText("Equipo 2:");

        nombreEquipo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        descripcionEvento.setColumns(20);
        descripcionEvento.setRows(5);
        jScrollPane1.setViewportView(descripcionEvento);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel7.setText("Equipo 1:");

        tipoDeporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUTBOL", "TENIS", "RUGBY", "BASEBALL" }));
        tipoDeporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tipoDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDeporteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel8.setText("Código del evento:");

        jLabel9.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel9.setText("Fecha del evento:");

        crearEvento.setText("Crear Evento");
        crearEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEventoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad de personas:");

        cantidadPersonas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(codigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(montoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(calendarioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104))
                            .addComponent(botonVolver, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(crearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(montoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombreEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(crearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonVolver))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        MenuEventos me = new MenuEventos();
        me.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void tituloEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloEventoActionPerformed

    private void crearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEventoActionPerformed
        double montoEv;
                int cantidad;
                if (!tituloEvento.getText().isBlank() && !descripcionEvento.getText().isBlank() && !nombreEquipo2.getText().isBlank() && !nombreEquipo1.getText().isBlank() && !montoEvento.getText().isBlank() && !cantidadPersonas.getText().isBlank()) {
                    if (calendarioEvento.getDate() != null) {
                        try {
                            montoEv = Double.parseDouble(montoEvento.getText());
                        } catch (NumberFormatException er) {
                            JOptionPane.showMessageDialog(null, "El monto debe ser un número");
                            return;
                        }

                        try {
                            cantidad = Integer.parseInt(cantidadPersonas.getText());
                        } catch (NumberFormatException er) {
                            JOptionPane.showMessageDialog(null, "La cantidad de personas tiene que ser un número entero");
                            return;
                        }

                        if (cantidad >= 0 && montoEv >= 0) {
                            if (cantidad <= 20000) {
                                if (seleccionado != null) {

                                    Eventos eve = new EventoDeportivo(ID, tituloEvento.getText(), descripcionEvento.getText(), calendarioEvento.getDate(), montoEv, cantidad, nombreEquipo1.getText(), nombreEquipo2.getText(), seleccionado, 0, 1, new ArrayList(), new ArrayList(), false);
                                    Login.MANEJOEVENTOS.AddEvent(eve, ID);
                                    JOptionPane.showMessageDialog(null, "Se ha creado el evento");
                                    MenuEventos me = new MenuEventos();
                                    me.setVisible(true);
                                    calendarioEvento = null;

                                    if (Login.FUNCIONES.buscar(ManejoUsuarios.USERACTUAL).getTipoUsuario() == 1) {
                                        Administrador adm = (Administrador) Login.FUNCIONES.buscar(ManejoUsuarios.USERACTUAL);
                                        adm.AgregarID(ID);
                                    }
                                    if (Login.FUNCIONES.buscar(ManejoUsuarios.USERACTUAL).getTipoUsuario() == 2) {
                                        Contenidos cts = (Contenidos) Login.FUNCIONES.buscar(ManejoUsuarios.USERACTUAL);
                                        cts.AgregarID(ID);
                                    }
                                    dispose();
                                } else {
                                    JOptionPane.showMessageDialog(null, "No ha seleccionado ningún tipo de deporte");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No pueden haber más de 20,000 personas");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Tiene que ser una cantidad positiva");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Necesita seleccionar una fecha");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
                }
    }//GEN-LAST:event_crearEventoActionPerformed

    private void tipoDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeporteActionPerformed
        String tipoDeporteSeleccionado = (String) tipoDeporte.getSelectedItem();
    switch (tipoDeporteSeleccionado) {
        case "FUTBOL":
            seleccionado = TipoDeporte.FUTBOL;
            break;
        case "TENIS":
            seleccionado = TipoDeporte.TENIS;
            break;
        case "RUGBY":
            seleccionado = TipoDeporte.RUGBY;
            break;
        case "BASEBALL":
            seleccionado = TipoDeporte.BASEBALL;
            break;
        default:
            seleccionado = null;
            break;
    }
    }//GEN-LAST:event_tipoDeporteActionPerformed

    
    
    int ID = obtenerNuevoId();
    private int obtenerNuevoId() {
        int nuevoId = 0;
        while (Login.MANEJOEVENTOS.buscar(nuevoId) != null) {
            nuevoId++;
        }
        return nuevoId;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private com.toedter.calendar.JDateChooser calendarioEvento;
    private javax.swing.JTextField cantidadPersonas;
    private javax.swing.JTextField codigoEvento;
    private javax.swing.JButton crearEvento;
    private javax.swing.JTextArea descripcionEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField montoEvento;
    private javax.swing.JTextField nombreEquipo1;
    private javax.swing.JTextField nombreEquipo2;
    private javax.swing.JComboBox<String> tipoDeporte;
    private javax.swing.JTextField tituloEvento;
    // End of variables declaration//GEN-END:variables
}
