package Principal;

import Eventos.BorrarEvento;
import Eventos.CrearDeportivo;
import Eventos.CrearMusical;
import Eventos.CrearReligioso;
import Eventos.VerEvento;
import javax.swing.JOptionPane;

public class MenuEventos extends javax.swing.JFrame {

    /**
     * Creates new form MenuEventos
     */
    public MenuEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarEvento = new javax.swing.JButton();
        verEvento = new javax.swing.JButton();
        crearEvento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        borrarEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editarEvento.setText("Editar Evento");
        editarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEventoActionPerformed(evt);
            }
        });

        verEvento.setText("Ver Evento");
        verEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEventoActionPerformed(evt);
            }
        });

        crearEvento.setText("Crear Evento");
        crearEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEventoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel2.setText("Manejo de Eventos");

        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        borrarEvento.setText("Borrar Evento");
        borrarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(crearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(editarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(verEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(borrarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(botonVolver))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarEventoActionPerformed

    private void verEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEventoActionPerformed
        VerEvento ve = new VerEvento();
        ve.setVisible(true);
        dispose();
    }//GEN-LAST:event_verEventoActionPerformed

    private void crearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEventoActionPerformed
        String[] opciones = {"Deportivo", "Musical", "Religioso"};
        CrearReligioso cr = new CrearReligioso();
        CrearMusical cm = new CrearMusical();
        CrearDeportivo cd = new CrearDeportivo();
        

    int opcionSeleccionada = JOptionPane.showOptionDialog(this, "Elija el tipo de evento que desea crear:", "Crear Evento", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);

    switch(opcionSeleccionada) {
        case 0:
            cd.setVisible(true);
            dispose();
            break;
        case 1:
            cm.setVisible(true);
            dispose();
            break;
        case 2:
            cr.setVisible(true);
            dispose();
            break;
    }
    }//GEN-LAST:event_crearEventoActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        MenuInicio mu = new MenuInicio();
        mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void borrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarEventoActionPerformed
        BorrarEvento be = new BorrarEvento();
        be.setVisible(true);
        dispose();
    }//GEN-LAST:event_borrarEventoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarEvento;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton crearEvento;
    private javax.swing.JButton editarEvento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton verEvento;
    // End of variables declaration//GEN-END:variables
}
