/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Reportes.EventosCancelados;
import Reportes.EventosFuturos;
import Reportes.EventosRealizados;
import Reportes.Perfil;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MenuReportes extends javax.swing.JFrame {

    /**
     * Creates new form MenuReportes
     */
    public MenuReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventosFuturos = new javax.swing.JButton();
        eventosCancelados = new javax.swing.JButton();
        eventosRealizados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        perfilUsuario = new javax.swing.JButton();
        ingresoFecha1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eventosFuturos.setText("Eventos Futuros");
        eventosFuturos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eventosFuturos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosFuturosActionPerformed(evt);
            }
        });

        eventosCancelados.setText("Eventos Cancelados");
        eventosCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eventosCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosCanceladosActionPerformed(evt);
            }
        });

        eventosRealizados.setText("Eventos Realizados");
        eventosRealizados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eventosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosRealizadosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel2.setText("Reportes");

        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        perfilUsuario.setText("Perfil");
        perfilUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilUsuarioActionPerformed(evt);
            }
        });

        ingresoFecha1.setText("Ingreso por fecha");
        ingresoFecha1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresoFecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoFecha1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eventosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventosCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventosFuturos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eventosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(eventosFuturos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(eventosCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ingresoFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(perfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(botonVolver))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eventosFuturosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosFuturosActionPerformed
        EventosFuturos ef = new EventosFuturos();
        ef.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosFuturosActionPerformed

    private void eventosCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosCanceladosActionPerformed
        EventosCancelados ec = new EventosCancelados();
        ec.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosCanceladosActionPerformed

    private void eventosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosRealizadosActionPerformed
        EventosRealizados er = new EventosRealizados();
        er.setVisible(true);
        dispose();
    }//GEN-LAST:event_eventosRealizadosActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        MenuInicio mu = new MenuInicio();
        mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void perfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilUsuarioActionPerformed
        Perfil p = new Perfil();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_perfilUsuarioActionPerformed

    private void ingresoFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoFecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoFecha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton eventosCancelados;
    private javax.swing.JButton eventosFuturos;
    private javax.swing.JButton eventosRealizados;
    private javax.swing.JButton ingresoFecha1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton perfilUsuario;
    // End of variables declaration//GEN-END:variables
}
